language: c++

git:
  depth: 1

dist: trusty

sudo: true

install:
 - echo "deb http://de.archive.ubuntu.com/ubuntu xenial main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get install --allow-unauthenticated g++ libboost-all-dev cmake libreadline-dev libssl-dev autoconf

script:
 - cmake -DCMAKE_BUILD_TYPE=Debug -DBoost_USE_STATIC_LIBS=OFF .
 - make -j 2
 - tests/chain_test | cat
 - tests/plugin_test | cat
 - cd libraries/fc
 - tests/all_tests | cat
 - tests/api | cat
 - tests/bip_lock | cat
 - tests/ecc_test README.md | cat
 - tests/log_test | cat
 - tests/sha_test | cat
